#!/usr/bin/env python3
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl
import argparse
import subprocess
import sys

parser = argparse.ArgumentParser()
parser.add_argument('--device', default='/dev/waggle_sysmon')
args = parser.parse_args()

sys.exit(subprocess.call('avrdude -v -pm32u4 -cavr109 -P {} -b57600 -D -Uflash:w:./firmware/bin/firmware.ino.hex:i'.format(args.device), shell=True))
