#!/usr/bin/env python3
import argparse
import subprocess
import sys

parser = argparse.ArgumentParser()
parser.add_argument('--device', default='/dev/waggle_sysmon')
args = parser.parse_args()

sys.exit(subprocess.call('avrdude -v -pm32u4 -cavr109 -P {} -b57600 -D -Uflash:w:./firmware/bin/firmware.ino.hex:i'.format(args.device), shell=True))
