#!/bin/bash
avrdude -C ./bootloader/src/caterina/avrdude.conf -B 2 -p atmega32u4 -P usb -c avrispmkII -U efuse:w:0xcb:m  -U hfuse:w:0xd8:m -U lfuse:w:0xff:m -v -U flash:w:./bootloader/src/caterina/Caterina.hex
sleep 2
make program
