#!/bin/bash

PLAIN='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'

# install bootloader
if ./installbl $@; then
  echo "${GREEN}>>> BOOTLOADER PASS${PLAIN}"
else
  echo "${RED}>>> BOOTLOADER FAIL${PLAIN}"
  sleep 30
  exit 1
fi

# install firmware
sleep 5

if ./installfw $@; then
  echo "${GREEN}>>> FIRMWARE PASS${PLAIN}"
else
  echo "${RED}>>> FIRMWARE FAIL${PLAIN}"
  sleep 30
  exit 1
fi

sleep 10

# initialize wagman
if ./wminit $@; then
  echo "${GREEN}>>> SETUP PASS${PLAIN}"
else
  echo "${RED}>>> SETUP FAIL${PLAIN}"
  sleep 30
  exit 1
fi

sleep 10
