#!/bin/bash

# install bootloader
if ./installbl $@; then
  echo '>>> BOOTLOADER PASS'
else
  echo '>>> BOOTLOADER FAIL'
  sleep 30
  exit 1
fi

# install firmware
sleep 5

if ./installfw $@; then
  echo '>>> FIRMWARE PASS'
else
  echo '>>> FIRMWARE FAIL'
  sleep 30
  exit 1
fi

sleep 10

# initialize wagman
if ./wminit $@; then
  echo '>>> SETUP PASS'
else
  echo '>>> SETUP FAIL'
  sleep 30
  exit 1
fi

sleep 10
