#!/bin/sh

utils/wagmancli eereset

utils/wagmancli date $(date '+%Y %m %d %H %M %S')

echo 'wagman date'
utils/wagmancli date

echo 'local date'
date '+%Y %m %d %H %M %S'

echo 'wagman version'
utils/wagmancli ver

utils/wagmancli reset
