#!/bin/bash
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl

set -ex

utils/wagmancli $@ eereset

utils/wagmancli $@ date $(date '+%Y %m %d %H %M %S')

echo 'wagman date'
utils/wagmancli $@ date

echo 'local date'
date '+%Y %m %d %H %M %S'

echo 'wagman version'
utils/wagmancli $@ ver

utils/wagmancli $@ reset
