#!/usr/bin/env python3
from serial import Serial
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--device', default='/dev/waggle_sysmon', help='path to device')
parser.add_argument('--timeout', default=10, type=int, help='timeout in seconds')
parser.add_argument('args', nargs='+')
args = parser.parse_args()

with Serial(args.device, baudrate=57600, timeout=args.timeout) as ser:
    command = '@cli {}\n'.format(' '.join(args.args)).encode()
    ser.write(command)

    lines = []

    while True:
        try:
            line = ser.readline().decode()
        except UnicodeDecodeError:
            continue
        if len(line) == 0:
            raise TimeoutError('Wagman request timed out.')
        if line.startswith('log:'):
            continue
        if line.startswith('<<<- sid=cli'):
            break

    while True:
        try:
            line = ser.readline().decode()
        except UnicodeDecodeError:
            continue
        if len(line) == 0:
            raise TimeoutError('Wagman request timed out.')
        if line.startswith('log:'):
            continue
        if line.startswith('->>>'):
            break

        lines.append(line)

    output = ''.join(lines).strip()
    print(output)
