#!/usr/bin/env python3
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl
import re


with open('wagman.ino') as f:
    text = f.read()

commands = []

for block in re.findall('/\*((?:.|\n)*?)\*/', text):
    if not re.search('Command:', block):
        continue

    if not re.search('Description:', block):
        continue

    sections = []

    section = ''
    lines = []

    for line in block.splitlines():
        m = re.search('(\w+):', line)
        if m is not None:
            if section:
                sections.append((section, '\n'.join(lines).strip()))
            section = m.group(1)
            lines = []
        else:
            lines.append(line)

    if section:
        sections.append((section, '\n'.join(lines).strip()))

    commands.append(sections)


def sortkey(sections):
    for section, body in sections:
        if section == 'Command':
            return body
    return ''


print('# Commands List')

for sections in sorted(commands, key=sortkey):
    for section, body in sections:
        if section == 'Command':
            print('## {}'.format(body))
            print()

        if section == 'Description':
            print(body)
            print()

        if section == 'Examples':
            print('```sh')
            print(body)
            print('```')
