#!/bin/sh
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl

firmware=$1
port=$2

if [ -z "$firmware" ] || [ -z "$port" ]; then
	echo "usage: $0 firmware port"
	exit 1
fi

arduino-cli upload -v -b arduino:sam:wagman_v2 -i $firmware -p $port
